spring:
  application:
    name: provider
  mqtt:
    provider:
      #MQTT??????????11883????????????
      url: tcp://39.100.229.199:1883
      #???
      username: hjmqtt
      #??
      password: Hjmqtt@2020
      #???id(????)
      client-id: provider_id
      #MQTT??????????????????
      topic: test
    consumer:
      #MQTT??????????11883????????????
      url: tcp://39.100.229.199:1883
      #???
      username: hjmqtt
      #??
      password: Hjmqtt@2020
      #???id(????)
      client-id: consumer_id
      #MQTT??????????????????
      topic: test
server:
  port: 8080